/** 共通フォント一覧を取得する関数 */
export const getCommonFonts = () => [
    "Yu Gothic UI",
    "メイリオ",
    "Meiryo UI",
    "游ゴシック",
    "游明朝",
    "MS ゴシック",
    "MS Pゴシック",
    "MS 明朝",
    "MS P明朝",
    "Arial",
    "Times New Roman",
    "Calibri",
    "Cambria",
    "Segoe UI",
    "Consolas",
    "Verdana",
    "Tahoma",
    "Georgia",
    "Courier New",
    "Impact",
    "Trebuchet MS",
    "Comic Sans MS",
    "Arial Black",
    "Garamond",
    "Palatino Linotype",
    "Century Gothic",
    "Franklin Gothic Medium",
    "Lucida Console",
    "Lucida Sans Unicode",
    "Microsoft Sans Serif",
    "Bahnschrift",
    "Malgun Gothic",
    "SimSun",
    "San Francisco (SF Pro)",
    "ヒラギノ角ゴ",
    "ヒラギノ明朝",
    "Ubuntu",
    "Noto Sans",
    "Noto Serif",
    "Noto Mono",
    "Liberation Sans",
    "Liberation Serif",
    "Liberation Mono",
    "DejaVu Sans",
    "DejaVu Serif",
    "DejaVu Sans Mono",
    "San Francisco (SF Pro)",
    "Hiragino Sans",
    "Roboto",
    "Noto Sans CJK"
];